apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
spec:
  selector:
    matchLabels:
      app: flask-app
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask-app
          image: docker.io/danman28/flask-app-green:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
