apiVersion: apps/v1
kind: Deployment
metadata:
  name: site-deployment
spec:
  selector:
    matchLabels:
      app: site-deployment
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: site-deployment
    spec:
      containers:
        - name: site-deployment
          image: danman28/howdy-site
          ports:
            - containerPort: 80
